@startuml
title Sistema de Bolsa de trabajo

' ======================================
' ENTIDADES
' ======================================

entity "Empresa" as Empresa {
  idEmpresa : Int
  nombre : String
  rubro : String
  email : String
  contraseña : String
  --
  crearConvocatoria()
  verPostulantes()
}

entity "Usuario" as Usuario {
  idUsuario : Int
  nombre : String
  apellido : String
  email : String
  contraseña : String
  sexo : String
  tipoUsuario : String
  --
  iniciarSesion()
  postularse()
  verResultados()
}

entity "Convocatoria" as Convocatoria {
  idConvocatoria : Int
  titulo : String
  descripcion : String
  puesto : String
  ubicacion : String
  requisitos : String
  fechaInicio : Date
  fechaFin : Date
  estado : String
  modalidad : String
  linkExterno : String
  --
  linkExterno()
  empresa()
}

entity "Postulacion" as Postulacion {
  idPostulacion : Int
  fecha : Int
  estado : String
  puntaje : Int
  cv : String
  --
  registrar()
}

entity "Entrevista" as Entrevista {
  idEntrevista : Int
  fechaHora : Int
  puntaje : Int
  estado : String
  --
  evaluar()
}

' ======================================
' RELACIONES
' ======================================

Empresa "1" -- "0..*" Convocatoria : publica
Usuario "1" -- "0..*" Postulacion : realiza
Convocatoria "1" -- "0..*" Postulacion : recibe
Postulacion "1" -- "0..1" Entrevista : genera

@enduml
